[package]
name = "inapp"
version = "0.1.0"
authors = ["Vladimir Tolmachev <tolm_vl@hotmail.com>"]
edition = "2018"

[dependencies]
clap = "2.29"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.8"
maplit = "1.0.1"
md5 = "0.6.1"
bitflags = "1.1.0"